name: Build and Push to GHCR

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  packages: write  # Allows pushing to GHCR
  contents: read   # Allows reading the repository content

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Official Image
        uses: docker/build-push-action@v6
        with:
          context: ./examples/official
          file: ./examples/official/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/uv-official:latest
            ghcr.io/${{ github.repository_owner }}/uv-official:${{ github.sha }}
          cache-from: type=gha,scope=uv-official
          cache-to: type=gha,mode=min,scope=uv-official
          outputs: type=docker,dest=/tmp/uv-official.tar
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Official UV Docker Example
            org.opencontainers.image.licenses=MIT

      - name: Build and Push Custom Image  
        uses: docker/build-push-action@v6
        with:
          context: ./examples/custom
          file: ./examples/custom/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/uv-custom:latest
            ghcr.io/${{ github.repository_owner }}/uv-custom:${{ github.sha }}
          cache-from: type=gha,scope=uv-custom
          cache-to: type=gha,mode=min,scope=uv-custom
          outputs: type=docker,dest=/tmp/uv-custom.tar
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Custom UV Docker Example
            org.opencontainers.image.licenses=MIT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: /tmp/*.tar

  test:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: /tmp

      - name: Load images
        run: |
          docker load --input /tmp/uv-official.tar
          docker load --input /tmp/uv-custom.tar
          docker image ls -a

      - name: Test Images
        run: |
          docker compose up -d
          curl -f http://localhost:8000 || exit 1
          curl -f http://localhost:8001 || exit 1
          docker compose down